x-app:
  &app
  image: dqlite-app:local
  user: "${UID:-1000}"
  command: -v 2
  volumes:
    - ../certs:/opt/app/certs:ro
    - ../../.data:/opt/app/data:rw,delegated

x-common-env:
  &env
  SERVICE_NAME: null
  NAMESPACE: null
  CLUSTER_DOMAIN: null

services:
  ingress-controller:
    image: haproxy:lts-alpine
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - 8080:8080
    environment: *env

  app-0:
    <<: *app
    environment:
      POD_NAME: app-0
      <<: *env
    networks:
      default:
        aliases:
          - "${SERVICE_NAME}.${NAMESPACE}.svc.${CLUSTER_DOMAIN}"
          - "app-0.${SERVICE_NAME}.${NAMESPACE}.svc.${CLUSTER_DOMAIN}"

  app-1:
    <<: *app
    environment:
      POD_NAME: app-1
      <<: *env
    networks:
      default:
        aliases:
          - "${SERVICE_NAME}.${NAMESPACE}.svc.${CLUSTER_DOMAIN}"
          - "app-1.${SERVICE_NAME}.${NAMESPACE}.svc.${CLUSTER_DOMAIN}"

  app-2:
    <<: *app
    environment:
      POD_NAME: app-2
      <<: *env
    networks:
      default:
        aliases:
          - "${SERVICE_NAME}.${NAMESPACE}.svc.${CLUSTER_DOMAIN}"
          - "app-2.${SERVICE_NAME}.${NAMESPACE}.svc.${CLUSTER_DOMAIN}"
