name: dqlite

x-app:
  &app
  image: dqlite-app:local
  volumes:
    - ../../.certs:/app/certs:ro
    - ../../.data:/app/data:rw,delegated
    - ../../bin:/app/bin:ro
  healthcheck:
    test: /app/bin/httpcheck http://localhost:8080/ready

x-env:
  &env
  K8S_SERVICE_NAME: dqlite-app-headless
  K8S_NAMESPACE: sandbox
  K8S_CLUSTER_DOMAIN: cluster.local

services:
  ingress-controller:
    image: haproxy:lts-alpine
    volumes: [ ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro ]
    ports: [ 8080:8080 ]

  app-0:
    <<: *app
    container_name: dqlite-app-0
    environment:
      <<: *env
      K8S_POD_NAME: dqlite-app-0
      DATA_DIR: /app/data/0
    networks:
      default:
        aliases:
          - dqlite-app-0.dqlite-app-headless.sandbox.svc.cluster.local
          - dqlite-app-headless

  app-1:
    <<: *app
    container_name: dqlite-app-1
    environment:
      <<: *env
      K8S_POD_NAME: dqlite-app-1
      DATA_DIR: /app/data/1
    networks:
      default:
        aliases:
          - dqlite-app-1.dqlite-app-headless.sandbox.svc.cluster.local
          - dqlite-app-headless

  app-2:
    <<: *app
    container_name: dqlite-app-2
    environment:
      <<: *env
      K8S_POD_NAME: dqlite-app-2
      DATA_DIR: /app/data/2
    networks:
      default:
        aliases:
          - dqlite-app-2.dqlite-app-headless.sandbox.svc.cluster.local
          - dqlite-app-headless

