---
apiVersion: v1
kind: Service
metadata:
  name: dqlite-app-headless
spec:
  selector:
    app: dqlite-app
  clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: sql
      protocol: TCP
      port: 9000
      targetPort: sql
---
apiVersion: v1
kind: Service
metadata:
  name: dqlite-app
spec:
  selector:
    app: dqlite-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: sql
      protocol: TCP
      port: 9000
      targetPort: sql
